import { StateSchema, MessagesValue, ReducedValue, StateGraph, START, END, type GraphNode } from "@langchain/langgraph";
import { HumanMessage } from "@langchain/core/messages";
import { mistralModel, cohoreModel, geminiModel } from "./models.service.js"
import { createAgent,providerStrategy } from "langchain";
import { z } from "zod";



const State = new StateSchema({
    messages: MessagesValue,
    solution_1: new ReducedValue(z.string().default(""),{
        reducer: (current,next) => {
            return next
        }
    }),
    solution_2: new ReducedValue(z.string().default(""),{
        reducer: (current,next) => {
            return next
        }
    }),
    judge_recommendation: new ReducedValue(z.object().default({
        solution_1_score: 0,
        solution_2_score: 0,
    }),
        {
            reducer: (current, next) => {
                return next
           }
        }
    )    
});

const solutionNode: GraphNode<typeof State> = async (state: typeof State) => {
    console.log(state)

    const [mistral_solution, cohore_solution] = await Promise.all([
        mistralModel.invoke(state.messages[0].text),
        cohoreModel.invoke(state.messages[0].text)

    ])

    return {
        solution_1: mistral_solution.text,
        solution_2: cohore_solution.text
    }
}



const judgeNode: GraphNode<typeof State> = async (state: typeof State) => {
    const { solution_1, solution_2 } = state;

    const judge = createAgent({
        model: geminiModel,
        tools: [],
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
        }))
    })

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(
                `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
            )
        ]
    })

    const result = judgeResponse.structuredResponse

    return {
        judge_recommendation: result
    }
}



const graph = new StateGraph(State)
.addNode("solution", solutionNode)
.addNode("judge", judgeNode)
.addEdge(START, "solution")
.addEdge("solution", "judge")
.addEdge("judge", END)
.compile();


export default async function(userMessage: string) {
    const result = await graph.invoke({
        messages: [
            new HumanMessage(userMessage)
        ],
    })

    console.log(result);

    return result.messages;
}



// type JUDGEMENT = {
//     winner: "solution_1" | "slution_2";
//     solution_1_score: number;
//     solution_2_score: number;
// }

// type AIBATTLESTATE = {
//     message: typeof MessagesValue;
//     solution_1: string;
//     solution_2: string;
//     judgement: JUDGEMENT;
// }

// const state: AIBATTLESTATE = {
//     message: MessagesValue,
//     solution_1: "",
//     solution_2: "",
//     judgement: {
//         winner: "solution_1",
//         solution_1_score: 0,
//         solution_2_score: 0
//     }
// }
